blank_issues_enabled: false
contact_links:
  - name: Custom Issue Template
    url: https://github.com/costateixeira/smart-html/issues/new?template=release.md
    about: A template for creating issues with specific fields.
