name: Custom Issue Template
description: A template for creating issues with specific fields.
title: "[Category] Title"

body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Enter the title of the issue.
      placeholder: "Issue title"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category of the issue.
      options:
        - base
        - L2
        - L3
        - other
    validations:
      required: true

  - type: textarea
    id: introduction
    attributes:
      label: Introduction
      description: Provide a brief introduction (2 to 3 lines).
      placeholder: "A short description of the issue."
    validations:
      required: true
      minLength: 10
      maxLength: 300

  - type: input
    id: version
    attributes:
      label: Version
      description: Specify the version.
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: branch
    attributes:
      label: Branch
      description: Select the branch.
      options:
        - main
        - develop
        - feature/branch-name
        # Add more branches as needed.
    validations:
      required: true

  - type: markdown
    id: description
    attributes:
      value: "## Description \n\n Provide a detailed description (supports Markdown)."
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Mode
      description: Select the mode.
      options:
        - working
        - milestone
        - technical-correction
        - withdrawal
    validations:
      required: true

  - type: dropdown
    id: first
    attributes:
      label: First
      description: Is this the first time?
      options:
        - "true"
        - "false"
    validations:
      required: true

  - type: input
    id: path
    attributes:
      label: Path
      description: Enter the URL path.
      placeholder: "https://example.com/path"
    validations:
      required: true
      pattern: "^https?://"

  - type: input
    id: ci-build
    attributes:
      label: CI Build
      description: Enter the CI build URL.
      placeholder: "https://ci.example.com/build"
    validations:
      required: true
      pattern: "^https?://"

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Select the current status.
      options:
        - release
        - trial-use
        - update
        - qa-preview
        - ballot
        - draft
        - normative+trial-use
        - normative
        - informative
    validations:
      required: true

  - type: input
    id: sequence
    attributes:
      label: Sequence
      description: Prepopulated text for the sequence.
      value: "Releases"
    validations:
      required: true
