name: FHIR IG Publication Request
description: FHIR IG publication request.
title: "[IG Publication Request] Title of Your IG"
labels: ["FHIR IG Request"]

body:
  - type: input
    id: title
    attributes:
      label: IG Title
      description: Enter the title of the Implementation Guide.
      placeholder: "Title of the IG"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the category of the IG.
      options:
        - base
        - L2
        - L3
        - other
    validations:
      required: true

  - type: textarea
    id: introduction
    attributes:
      label: Introduction
      description: Provide a brief introduction (2 to 3 lines) about the IG.
      placeholder: "Brief introduction to the IG."
    validations:
      required: true
      minLength: 10
      maxLength: 300

  - type: input
    id: version
    attributes:
      label: Version
      description: Specify the version of the IG you are requesting publication for.
      placeholder: "e.g., v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: branch
    attributes:
      label: Branch
      description: Select the branch from which the IG will be published.
      options:
        - main
        - develop
        - feature/branch-name
        # Add more branches as needed.
    validations:
      required: true

  - type: markdown
    id: description
    attributes:
      value: "## Description \n\n Provide a detailed description of the IG, including its scope and intended use."
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Mode
      description: Select the mode of the publication request.
      options:
        - working
        - milestone
        - technical-correction
        - withdrawal
    validations:
      required: true

  - type: dropdown
    id: first
    attributes:
      label: Is this the first time publishing this IG?
      description: Indicate whether this is the first publication request for this IG.
      options:
        - "true"
        - "false"
    validations:
      required: true

  - type: input
    id: path
    attributes:
      label: IG Publication Path
      description: Enter the URL where the IG will be hosted.
      placeholder: "https://example.com/path"
    validations:
      required: true
      pattern: "^https?://"

  - type: input
    id: ci-build
    attributes:
      label: Continuous Integration (CI) Build URL
      description: Enter the URL of the CI build for this IG.
      placeholder: "https://ci.example.com/build"
    validations:
      required: true
      pattern: "^https?://"

  - type: dropdown
    id: status
    attributes:
      label: Publication Status
      description: Select the current publication status of the IG.
      options:
        - release
        - trial-use
        - update
        - qa-preview
        - ballot
        - draft
        - normative+trial-use
        - normative
        - informative
    validations:
      required: true

  - type: input
    id: sequence
    attributes:
      label: Sequence
      description: The sequence for publication (prepopulated with "Releases").
      value: "Releases"
    validations:
      required: true
