name: FHIR IG Publication Request Workflow

on:
  issues:
    types: [opened]

jobs:
  create-publication-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install awk
        run: sudo apt-get update && sudo apt-get install -y gawk

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Extract form data from issue body
        id: extract_data
        run: |
          # Extract values using awk
          VERSION=$(echo "${{ github.event.issue.body }}" | awk -F': ' '/^### Version/{getline; print $0}')
          PATH=$(echo "${{ github.event.issue.body }}" | awk -F': ' '/^### IG Publication Path/{getline; print $0}')
          CI_BUILD=$(echo "${{ github.event.issue.body }}" | awk -F': ' '/^### Continuous Integration \(CI\) Build URL/{getline; print $0}')
          STATUS=$(echo "${{ github.event.issue.body }}" | awk -F': ' '/^### Publication Status/{getline; print $0}')
          SEQUENCE=$(echo "${{ github.event.issue.body }}" | awk -F': ' '/^### Sequence/{getline; print $0}')

          # Save extracted values as environment variables
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "CI_BUILD=$CI_BUILD" >> $GITHUB_ENV
          echo "STATUS=$STATUS" >> $GITHUB_ENV
          echo "SEQUENCE=$SEQUENCE" >> $GITHUB_ENV

      - name: Create the publication-request.json
        run: |
          echo '{
            "package-id": "your-package-id",
            "version": "'$VERSION'",
            "path": "'$PATH'",
            "ci-build": "'$CI_BUILD'",
            "status": "'$STATUS'",
            "sequence": "'$SEQUENCE'"
          }' > publication-request.json

      - name: Display the publication-request.json content
        run: |
          echo "Content of publication-request.json:"
          cat publication-request.json

      - name: Log Success
        run: echo "Success"
